---
- name: Copy license file
  copy:
    src: "{{ opdk_license_source_file_name }}"
    dest: "{{ opdk_license_target_file_path }}"
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0644
    force: yes

- include: 4150703-main.yml
  when: opdk_version | version_compare('4.15.07', '<=')

- name: Install Apigee Setup
  shell: 'bash {{ apigee_service }} apigee-setup install'
  args:
    creates: '{{ apigee_installation_home }}/apigee-setup/bin/setup.sh }}'
  when: opdk_version | version_compare('4.16', '>=')

- name: Install Apigee Admin
  shell: 'bash {{ apigee_service }} apigee-adminapi install'
  args:
    creates: '{{ apigee_installation_home }}/apigee-adminapi/bin/apigee-adminapi.sh }}'
  when: opdk_version | version_compare('4.16', '>=')

- name: Set Apigee directory ownership
  file:
    path: '{{ item }}'
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_user_name }}'
    recurse: yes
  with_items:
  - /opt/apigee
  - /opt/nginx