---
- name: Copy license file
  copy:
    src: "{{ opdk_license_source_file_name }}"
    dest: "{{ opdk_license_target_file_path }}"
    mode: 0644
    force: yes

- block:

  - name: Uninstall Apigee Setup, if it exists
    ignore_errors: "{{ ignore_errors | default(yes) }}"
    shell: '{{ apigee_service }} apigee-setup uninstall'
    when: opdk_version | version_compare('4.16', '>=')

  - name: Uninstall Apigee Admin, if it exists
    ignore_errors: "{{ ignore_errors | default(yes) }}"
    shell: '{{ apigee_service }} apigee-adminapi uninstall'
    when: opdk_version | version_compare('4.16', '>=')

  - name: Uninstall Apigee Provision, if it exists
    ignore_errors: "{{ ignore_errors | default(yes) }}"
    shell: '{{ apigee_service }} apigee-provision uninstall'
    when: opdk_version | version_compare('4.16', '>=')

  - name: Uninstall Apigee Migrate, if it exists
    ignore_errors: "{{ ignore_errors | default(yes) }}"
    shell: '{{ apigee_service }} apigee-migrate uninstall'
    when: opdk_version | version_compare('4.16', '>=')

  when: upgrade_edge is defined and upgrade_edge | bool == True

- block:

  - name: Install Apigee Setup
    ignore_errors: "{{ ignore_errors | default('no') }}"
    shell: '{{ apigee_service }} apigee-setup install'

  - name: Install Apigee Admin
    ignore_errors: "{{ ignore_errors | default('no') }}"
    shell: '{{ apigee_service }} apigee-adminapi install'

  when: opdk_version | version_compare('4.16', '>=')
