---
- name: Copy license file
  copy:
    src: "{{ opdk_license_source_file_name }}"
    dest: "{{ opdk_license_target_file_path }}"
    mode: 0644
    force: yes

- block:

  - name: Uninstall Apigee Setup
    ignore_errors: yes
    shell: '{{ apigee_service }} apigee-setup uninstall'
    when: opdk_version | version_compare('4.16', '>=')

  - name: Uninstall Apigee Admin
    ignore_errors: yes
    shell: '{{ apigee_service }} apigee-adminapi uninstall'
    when: opdk_version | version_compare('4.16', '>=')

  when: upgrade_edge is defined and upgrade_edge | bool == True

- block:

  - name: Install Apigee Setup
    shell: '{{ apigee_service }} apigee-setup install'
    args:
      creates: '{{ apigee_installation_home }}/apigee-setup/bin/setup.sh'

  - name: Install Apigee Admin
    shell: '{{ apigee_service }} apigee-adminapi install'
    args:
      creates: '{{ apigee_installation_home }}/apigee-adminapi/bin/apigee-adminapi.sh'

  - name: Wait for ready
    shell: '{{ apigee_all }} wait_for_ready'

  when: opdk_version | version_compare('4.16', '>=')
